name: Teste e Publicação Python

on:
  push:
    tags:
      - 'v*'  # Executa quando uma tag na forma v* é criada (ex: v0.1.0)

jobs:
  test:
    name: Testes e Cobertura
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
    
    - name: Executar testes com cobertura
      run: |
        pytest tests/ --cov=src --cov-report=xml --cov-report=term
    
    - name: Upload do relatório de cobertura
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

  build:
    name: Build do Pacote
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Instalar dependências de build
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build do pacote
      run: |
        python -m build
    
    - name: Upload de artefatos
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  publish:
    name: Publicação no PyPI
    runs-on: ubuntu-latest
    needs: build
    
    # Especificar o ambiente é opcional, mas fortemente recomendado
    environment:
      name: pypi
      url: https://pypi.org/p/safelogger
    
    # IMPORTANTE: esta permissão é obrigatória para Trusted Publishing
    permissions:
      id-token: write
    
    steps:
    - name: Download dos artefatos
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/
    
    - name: Publicar no PyPI
      uses: pypa/gh-action-pypi-publish@release/v1 