name: Teste e Publicação Python

on:
  push:
    tags:
      - 'v*'  # Executa quando uma tag na forma v* é criada (ex: v0.1.0)

jobs:
  test:
    name: Testes e Cobertura
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    
    - name: Executar testes com cobertura
      run: |
        pytest tests/ --cov=src --cov-report=xml --cov-report=term
    
    - name: Upload do relatório de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

  build:
    name: Build do Pacote
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Instalar dependências de build
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build do pacote
      run: |
        python -m build
    
    - name: Upload de artefatos
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish:
    name: Publicação no PyPI
    runs-on: ubuntu-latest
    needs: build
    
    # Habilitar o token único para Trusted Publishing
    permissions:
      id-token: write  # Necessário para autenticação OIDC com PyPI
    
    # Ambiente dedicado para publicação (com possíveis proteções adicionais)
    environment:
      name: pypi
      url: https://pypi.org/p/lib-logging  # Substitua pelo URL do seu projeto no PyPI
    
    steps:
    - name: Download dos artefatos
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    
    - name: Publicar no PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
      # Não é necessário configurar autenticação explícita ao usar Trusted Publishing
      # Para usar token API (método tradicional), adicione:
      # with:
      #   password: ${{ secrets.PYPI_API_TOKEN }} 